### ISSUE TITLE
update version

### ISSUE THREAD

**Issue by sansan88** [fluster/deckdeckgo-starter#24]
what do I have to do to update my deckdeckgo version?
this is my package.js file:

`{
  "name": "deckdeckgo-starter",
  "version": "1.0.0-beta.9",
  "description": "DeckDeckGo, the new tool to create lightweight presentation using HTML and Ionic components",
  "homepage": "https://deckdeckgo.com",
  "scripts": {
    "start": "concurrently --kill-others \"npm run watch\" \"npm run dev\"",
    "start-no-remote": "concurrently --kill-others \"npm run watch-no-remote\" \"npm run dev\"",
    "dev": "lite-server",
    "watch": "webpack --watch --mode development",
    "watch-no-remote": "webpack --watch --mode development --env.no-remote=true",
    "build": "webpack --mode production",
    "local": "concurrently --kill-others \"webpack --watch --mode development --env.local=true\" \"npm run dev\""
  },
  "author": {
    "name": "David Dal Busco",
    "email": "david.dalbusco@outlook.com",
    "web": "https://fluster.io"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/fluster/deckdeckgo-starter.git"
  },
  "devDependencies": {
    "clean-webpack-plugin": "^1.0.0",
    "concurrently": "^4.1.0",
    "copy-webpack-plugin": "^4.6.0",
    "css-loader": "^1.0.1",
    "file-loader": "^2.0.0",
    "html-webpack-plugin": "^4.0.0-beta.2",
    "lite-server": "^2.4.0",
    "style-loader": "^0.23.1",
    "webpack": "^4.26.1",
    "webpack-cli": "^3.1.2",
    "workbox-webpack-plugin": "^3.6.3"
  },
  "license": "MIT",
  "dependencies": {
    "@ionic/core": "^4.0.0-beta.16",
    "@webcomponents/custom-elements": "^1.2.1",
    "deckdeckgo": "^1.0.0-beta.12",
    "deckdeckgo-remote": "^1.0.0-alpha.3",
    "ionicons": "^4.4.8"
  },
  "keywords": [
    "ionic",
    "stencil",
    "stenciljs",
    "web components",
    "pwa",
    "progressive web app",
    "presentation",
    "slides",
    "slideshow",
    "talk"
  ]
}
`

**Comment by peterpeterparker** [comment]
Good question, I'm thinking about what's the best way, I don't have released yet released the starter kit v1.0.0-beta.10 so it's not documented ;)

According your package.json you are already kind of up-to-date with the starter-kit v1.0.0-beta.9, only improvement I would suggest is updating the following files:

font.css -> https://github.com/fluster/deckdeckgo-starter/blob/master/src/css/font.css

theme.css -> https://github.com/fluster/deckdeckgo-starter/blob/master/src/css/theme.css

the other improvements are more things regarding the CLI and the creation of new project or some extra information added to the build script

**Comment by peterpeterparker** [comment]
I'm currently deploying the new version, here the CHANGELOG which should solve your question: https://github.com/fluster/deckdeckgo-starter/blob/master/CHANGELOG.md

Ping me if something should be improved
