### ISSUE TITLE
Bundle Ionic for a better offline support

### ISSUE THREAD

**Issue by peterpeterparker** [fluster/deckdeckgo-starter#3]
Right now Ionic (core, css and ionicons) aren't bundled with Webpack, they are still referenced as external scripts in index.html

For a better offline support, these should be bundled with the webpack build

I wasn't able to make it so far but a documentation "how to bundle Ionic core" should be published by Ionic soonish

But if someone knows how to solves, would love to hear from you or even don't hesitate to send me a PR

**Comment by dimfried** [comment]
did you think about using parcel (https://parceljs.org)? I am not sure if it works fine with ionic, but if it does, it could reduce the overhead of webpack config :)

**Comment by peterpeterparker** [comment]
@dimfried when it comes to Angular or Ionic often Webpack or Rollup are often the bundlers of choice I understood

Furthermore the the PWA support is an important part of the project. Google provide an easy tutorial to pack workbox with Webpack (https://developers.google.com/web/tools/workbox/guides/codelabs/webpack). That's why I picked that bundler for the starter kit.

**Comment by peterpeterparker** [comment]
@dimfried thx but not much to do here right now, Ionic will provide soon a "how to bundle Ionic core" documentation, wait & see ;)

**Comment by dimfried** [comment]
even better! 😃 I will wait then ;)

**Comment by peterpeterparker** [comment]
I had a look on how to include custom elements because I gonna include the new DeckDeckGo core and end up including Ionic in the bundle

DeckDeckGo offline support is now there :)
